spring:
  application:
    name: AuthenticationServer
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test2
    driverClassName: org.h2.Driver
    username: sa
    password: password
server:
  port: 8083
  servlet:
    context-path: /authentication
logging:
  level:
    root: info
